# Generated by Django 5.0.6 on 2024-08-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_creator_comments_comment_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='creator',
        ),
    ]
