# Generated by Django 5.0.6 on 2024-09-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_comment_text_comments_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commenter',
            new_name='author',
        ),
    ]
