# Generated by Django 5.0.6 on 2024-09-04 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_commenter_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='watchlist',
            field=models.ManyToManyField(related_name='listing_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
